name: CI

on: [pull_request]

jobs:
  external_c_checks:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 5
      - name: Build libraries
        run: |
          rm -rf Modelica/Resources/Library/*
          mkdir -p Modelica/Resources/Library/$LIBDIR
          pushd Modelica/Resources/BuildProjects/autotools
          git clean -fdx .
          ./autogen.sh
          ./configure --libdir="$PWD/../../Library/$LIBDIR" --enable-static --disable-shared --enable-static-zlib --disable-hdf5 CPPFLAGS="-I${GITHUB_WORKSPACE}/.CI/Test"
          make --output-sync
          sudo make install
          popd
        env:
          LIBDIR: linux64
      - name: Run tests
        run: |
          cd .CI/Test
          ./test.sh onlystatic
        env:
          LIBDIR: linux64
          CC: gcc
  html_documentation_checks:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 5
      - name: Setup python environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install python packages
        run: |
          pip install --user pytidylib
          pip install --user futures
      - name: Build html tidy
        run: |
          git clone --branch 5.8.0 --depth=1 https://github.com/htacg/tidy-html5.git
          pushd tidy-html5
          cmake .
          make
          sudo make install
          popd
          sudo ldconfig
      - name: Tidy html
        run: python ./.CI/check_html.py tidyHTML ./
      - name: Check tags
        run: python ./.CI/check_html.py checkTags ./
  syntax_checks:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 5
      - name: Get moparser
        run: git clone --depth=1 https://github.com/modelica-tools/ModelicaSyntaxChecker
      - name: Check file encoding
        run: "! find . -name '*.mo' -exec bash -c 'iconv -o /dev/null -f utf8 -t utf8 \"{}\" |& sed \"s,^,{}: ,\"' ';' | grep '.'"
      - name: Check for UTF-8 BOM
        run: "! find . -name '*.mo' -print0 | xargs -0 grep -l $'^\\xEF\\xBB\\xBF' | grep ."
      - name: Check syntax
        run: ModelicaSyntaxChecker/Linux64/moparser -v 3.4 -r Complex.mo Modelica ModelicaReference ModelicaServices ModelicaTest ModelicaTestConversion4.mo ModelicaTestOverdetermined.mo ObsoleteModelica4.mo
  deprecation_checks:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 5
      - name: Setup python environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Check deprecated Text.lineColor annotation
        run: python ./.CI/check_deprecated_line_color.py Complex.mo Modelica ModelicaReference ModelicaServices ModelicaTest ModelicaTestConversion4.mo ModelicaTestOverdetermined.mo
  spelling_checks:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 5
      - name: Setup python environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install python packages
        run: |
          pip install --user codespell
      - name: Check for spelling errors
        run: |
          printf "[codespell]\nenable-colors=\n" >> .codespellrc
          codespell -L mesures ./Modelica/Constants.mo
          codespell -L nin,inport,fo ./Modelica/StateGraph.mo
          codespell -L addd,nd,nin ./Modelica/Blocks/Continuous.mo
          codespell -L utput ./Modelica/Electrical/Digital.mo
          codespell -L ser ./Modelica/Electrical/Polyphase/Examples/PolyphaseRectifier.mo
          codespell -L ser ./Modelica/Electrical/Polyphase/Examples/Utilities/PolyphaseRectifierData.mo
          codespell -L pres ./Modelica/Fluid/Dissipation.mo
          codespell -L fo,alo,als,cacl,ba,nd ./Modelica/Media/IdealGases/package.mo
          codespell -L fo,alo,als,cacl,ba,nd,alow ./Modelica/Media/IdealGases/Common/SingleGasesData.mo
          codespell -L alow ./Modelica/Media/IdealGases/Common/Functions.mo
          codespell -L alow ./Modelica/Media/IdealGases/Common/package.mo
          codespell -L dout ./Modelica/Media/Water/IF97_Utilities.mo
          codespell -L archiv ./Modelica/Electrical/Polyphase/UsersGuide/References.mo
          codespell -L mot ./Modelica/Electrical/Machines/Examples/ControlledDCDrives
          codespell -L singal ./Modelica/Electrical/Analog/UsersGuide/References.mo
          codespell -L numer ./Modelica/Math/package.mo
          codespell -L inport,nd,wit ./Modelica/Mechanics/Rotational
          codespell -L wit ./Modelica/Mechanics/Translational
          codespell -L ist ./Modelica/Mechanics/MultiBody
          codespell -L klick ./Modelica/Magnetic/FluxTubes/UsersGuide/Contact.mo
          codespell -L technik ./Modelica/Magnetic/FundamentalWave/UsersGuide/References.mo
          codespell --skip ./ObsoleteModelica4.mo,./Modelica/Constants.mo,./Modelica/Blocks/Continuous.mo,./Modelica/StateGraph.mo,./Modelica/Electrical/Digital.mo,./Modelica/Electrical/Polyphase/Examples/PolyphaseRectifier.mo,./Modelica/Electrical/Polyphase/Examples/Utilities/PolyphaseRectifierData.mo,./Modelica/Fluid/Dissipation.mo,./Modelica/Resources,./Modelica/Media/IdealGases/package.mo,./Modelica/Media/IdealGases/Common/SingleGasesData.mo,./Modelica/Media/IdealGases/Common/Functions.mo,./Modelica/Media/IdealGases/Common/package.mo,./Modelica/Media/Water/IF97_Utilities.mo,./Modelica/Electrical/Polyphase/UsersGuide/References.mo,./Modelica/Electrical/Machines/Examples/ControlledDCDrives,./Modelica/Electrical/Analog/UsersGuide/References.mo,./Modelica/Math/package.mo,./Modelica/Mechanics/Rotational,./Modelica/Mechanics/Translational,./Modelica/Mechanics/MultiBody,./Modelica/Magnetic/FluxTubes/UsersGuide/Contact.mo,./Modelica/Magnetic/FundamentalWave/UsersGuide/References.mo,./.CI,./.github,./.git,*.png -L nin,inport,te,sinc,vie,commutating
