name: Trigger CI ReSim

on:
  pull_request:

jobs:
  trigger_resim_checks:
    runs-on: ubuntu-latest

    steps:
      - name: Save PR number to a file
        run: |
          echo "${{ github.event.pull_request.number }}" > pr_number.txt
          cat pr_number.txt

      - name: Upload PR number artifact
        uses: actions/upload-artifact@v7
        with:
          name: pr-number
          path: pr_number.txt
