name: Trigger CI ReSim

on:
  pull_request:

jobs:
  trigger_resim_checks:
    runs-on: ubuntu-latest
    outputs:
      pr_number: ${{ steps.set_output.outputs.pr_number }}

    steps:
      - name: Set PR number output
        id: set_output
        run: |
          echo "pr_number=${{ github.event.pull_request.number }}" >> $GITHUB_OUTPUT
